### PR TITLE
echoaj First Pull Request :)

### PR DESCRIPTION
**Pull request by echoaj**
Deleted 2 things and added 3 things to To-do list

- [x] No Errors
- [x] Clean Code

### CODE REVIEW

**Comment by echoaj25** [comment]
Great job looks good

**Comment by echoaj** [comment]
Thank you very much

**Comment by echoaj25** [comment]
I will merge the pull request

**Comment by echoaj** [comment]
Hey did you close the pull request?

**Comment by echoaj25** [comment]
Yes by accident.  I will reopen

**Comment by echoaj** [comment]
Thanks!

**Pull request merged**
