### PR TITLE
added 3 items

### PR DESCRIPTION
**Pull request by echoaj**
Must get done by friday

- [x] fixed bug
- [x] clean code

### CODE REVIEW

**Comment by echoaj** [comment]
Does it look good?

**Comment by echoaj25** [comment]
Item must be capitalized

**Comment by echoaj** [comment]
ok will do

**Review by echoaj25 — CHANGES_REQUESTED** [review]
Capitalize all words.

**Review by echoaj25 — COMMENTED** [review]
Looks good

**Review by echoaj25 — APPROVED** [review]
Merging code!  Great job. Thanks!

**Review by echoaj — COMMENTED** [review]
Thanks

**Pull request merged**
